from tkinter import*
master=Tk()
def calculate_hitter_score():
    global v
    raw_data1=float(0.7*float(war3.get())+1.4*float(war2.get())+2*float(war1.get())+float(ops3.get())+1.5*float(ops2.get())+2*float(ops1.get())+float(ops.get())+float(war.get())/float(years.get()))
    v.set("Hitter Value="+str(int(raw_data1)))
def calculate_pitcher_score():
    global x
    raw_data2=0.01*float(ip.get())*(0.3*float(float(8)-float(fip3.get()))+0.7*float(float(8)-float(fip2.get()))+float(float(8)-float(fip1.get()))+0.3*float(float(10)-float(fip.get()))+0.7*float(war3.get())+1.4*float(war2.get())+2*float(war1.get())+float(war.get())/float(years.get()))
    x.set("Pitcher Value="+str(int(raw_data2)))          

Label(master, text="WAR Last Year").grid(row=0)
Label(master, text="WAR 2 Years Ago").grid(row=1)
Label(master, text="WAR 3 Years Ago").grid(row=2)
Label(master, text="WAR").grid(row=3)
Label(master, text="Years in MLB").grid(row=4)
Label(master, text="OPS Last Year").grid(row=5)
Label(master, text="OPS 2 Years Ago").grid(row=6)
Label(master, text="OPS 3 Years Ago").grid(row=7)
Label(master, text="OPS").grid(row=8)
Label(master, text="FIP Last Year").grid(row=9)
Label(master, text="FIP 2 Years Ago").grid(row=10)
Label(master, text="FIP 3 Years Ago").grid(row=11)
Label(master, text="FIP").grid(row=12)
Label(master,text="IP").grid(row=13)

v=StringVar()
v.set("Hitter Value=       ")
Label(master, textvariable=v).grid(row=15, column=0)
x=StringVar() 
x.set("Pitcher Value=     ")
Label(master,textvariable=x).grid(row=15, column=1)
b=Button(master, text="Calculate Hitter Value", command=calculate_hitter_score)
c=Button(master, text="Calculate Pitcher Value", command=calculate_pitcher_score)

war1=Entry(master)
war2=Entry(master)
war3=Entry(master)
war=Entry(master)
ops1=Entry(master)
ops2=Entry(master)
ops3=Entry(master)
ops=Entry(master)
years=Entry(master)
fip1=Entry(master)
fip2=Entry(master)
fip3=Entry(master)
fip=Entry(master)
ip=Entry(master)
 
war1.grid(row=0, column=1)
war2.grid(row=1, column=1)
war3.grid(row=2, column=1)
war.grid(row=3, column=1)
years.grid(row=4, column=1)
ops1.grid(row=5, column=1)
ops2.grid(row=6, column=1)
ops3.grid(row=7, column=1)
ops.grid(row=8, column=1)
fip1.grid(row=9, column=1)
fip2.grid(row=10, column=1)
fip3.grid(row=11, column=1)
fip.grid(row=12, column=1)
ip.grid(row=13,column=1)
b.grid(row=14, column=0)
c.grid(row=14, column=1)
